"""
Replace occurrences of PATTERN with REPLACEMENT in each FILE's name.

Useful because TextSnake annotations generated by [1] are named differently
than the original minirhizotron images, but partition.py relies on matching file
names to link them together.

[1] https://gitlab.informatik.uni-halle.de/moeller/minirhizotron_annotation

Usage:
    rename_files.py PATTERN REPLACEMENT FILE...
"""

import os
import sys

if len(sys.argv) < 3:
    sys.exit(__doc__)

PATTERN = sys.argv[1]
REPLACEMENT = sys.argv[2]

files = sys.argv[3:]

counter = 0
for f in files:
    f_new = f.replace(PATTERN, REPLACEMENT)
    try:
        os.rename(f, f_new)
        counter += 1
    except OSError as e:
        print(f'ERROR: {e}. Skipping', file=sys.stderr)
print(f'{counter} file(s) moved')
